### PR TITLE
Fix worldofbooks.com book search URL, add DVD url

### PR DESCRIPTION
**Pull request by janbaykara**
The URLs suggested for worldofbooks.com seem broken, based on a few clicks. Here's a proposed alternative, which should propose links for the user like:

- Book: https://www.worldofbooks.com/en-gb/category/all?search=Brain&pt=book
- DVD: https://www.worldofbooks.com/en-gb/category/all?search=Beverly%20Hill%20Ninjas&pt=dvd

### CODE REVIEW

**Comment by janbaykara** [comment]
One issue that isn't fixed by this PR is that the search term seems to be wrong. On the [Amazon page for The Cybernetic Brain (book)](https://www.amazon.co.uk/Cybernetic-Brain-Sketches-Another-Future/dp/0226667901/ref=sr_1_1?dchild=1&keywords=The+Cybernetic+Brain&qid=1625413972&sr=8-1), the worldofbooks.com URL currently resolves to:

```
https://www.worldofbooks.com/en-gb/books/xxx/xxx/%E2%80%8E9780718083298
```

This search term is clearly gibberish but I'm unsure how to extract the actual term without having looked through the code a bit.

**Comment by janbaykara** [comment]
Ah, I see. It is an ISBN. The issue is that %E2%80%8E is being appended before the ISBN for some reason.

**Comment by janbaykara** [comment]
It looks like there are some weird special characters being picked up in Amazon's HTML, which is why you have the strange leading characters being encoded like that. We could remove those.

Screenshot 2021-07-04 at 17 41 55

**Comment by janbaykara** [comment]
Alright, I've fixed the mis-serialising of ISBNs and now both books and DVDs work. This PR no longer uses the https://www.worldofbooks.com/en-gb/books/xxx/xxx/9780226667904 style of URL but it still redirects you to the product page if there is a direct match, which is nice.

**Comment by adriantombu** [comment]
Thanks for your time on this @janbaykara!
I'd rather keep the url as is for the books because making a search by ISBN doesn't work as [you can see here](https://www.worldofbooks.com/en-gb/category/all?search=9780226667904&pt=book) but I'll implement the change in the regex + add the DVD & video games categories from worldofbooks 😊

**Pull request closed without merging**
